# Connects over system sockets to databases, provides ports for IDE
services:
  postgres:
    build:
      args:
        user: ${USER}
      context: .
      dockerfile: docker/postgres/Dockerfile
    tty: true
    container_name: ahs_postgres
    environment:
      POSTGRES_DB: "${DB_NAME:-ahs}"
      POSTGRES_USER: "${DB_USER:-ahs-dev}"
      POSTGRES_PASSWORD: "${DB_PASS:-ahs}"
    user: "999:1000"
    ports:
      - "127.0.0.1:5433:5432"  # only for IDE
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./docker/.sockets:/var/run/postgresql/

  node:
    build:
      args:
        user: ${USER}
      context: .
      dockerfile: docker/node/Dockerfile
    tty: true
    container_name: ahs_node
    user: "1000:1000"
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/project

  redis:
    build:
      args:
        user: ${USER}
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: ahs_redis
    command: redis-server /etc/redis.conf
    ports:
      - "127.0.0.1:6399:6379"  # Only for IDE
    tty: true
    user: "999:1000"
    volumes:
      - ./docker/.sockets:/tmp/redis/
      - redis-data:/var/lib/redis/

volumes:
  postgres-data:
  redis-data: