# Generated by Django 5.1.5 on 2025-01-16 00:20

import backend.core.models.mixins
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_name', models.CharField(max_length=100)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username of an XUser', max_length=15, unique=True)),
                ('name', models.CharField(blank=True, help_text='Name of an XUser', max_length=50, null=True)),
                ('connection_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=19), max_length=7, size=None)),
                ('joined_x', models.DateTimeField()),
                ('description', models.CharField(blank=True, help_text='Description/Bio of an XUser', max_length=160, null=True, verbose_name='Biography')),
                ('entities', models.JSONField(null=True, verbose_name='Description Entities')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Location')),
                ('pinned_tweet_id', models.PositiveBigIntegerField(verbose_name='Pinned Tweet ID')),
                ('profile_image_url', models.URLField(null=True, verbose_name='Profile Image URL')),
                ('protected', models.BooleanField(default=False)),
                ('public_metrics', models.JSONField()),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'X User Profile',
                'verbose_name_plural': 'X User Profiles',
                'ordering': ('id', 'username', 'name', 'connection_status', 'joined_x', 'description', 'entities', 'location', 'pinned_tweet_id', 'profile_image_url', 'protected', 'public_metrics', 'url', 'verified', 'posts'),
                'unique_together': {('id', 'user_name')},
            },
            bases=(models.Model, backend.core.models.mixins.CreationDateMixin, backend.core.models.mixins.UpdateDateMixin),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('edit_history_tweet_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('attachments', models.JSONField()),
                ('text', models.TextField(editable=False, max_length=25000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='xapi.userprofile')),
            ],
            options={
                'verbose_name': 'Post / Tweet',
                'verbose_name_plural': 'Posts / Tweets',
            },
            bases=(models.Model, backend.core.models.mixins.CreationDateMixin, backend.core.models.mixins.UpdateDateMixin),
        ),
    ]
