# Generated by Django 5.1.5 on 2025-01-16 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarksProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bookmark profile',
                'verbose_name_plural': 'bookmark profiles',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update on')),
                ('icon_url', models.URLField(max_length=1000, null=True)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmarksprofile')),
            ],
            options={
                'verbose_name': 'bookmark',
                'verbose_name_plural': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update on')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('bm', models.ManyToManyField(related_name='category', to='bookmarks.bookmark')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmarksprofile')),
            ],
            options={
                'verbose_name': 'bookmark category',
                'verbose_name_plural': 'bookmark categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update on')),
                ('bm', models.ManyToManyField(related_name='tags', to='bookmarks.bookmark')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmarksprofile')),
            ],
            options={
                'verbose_name': 'bookmark tag',
                'verbose_name_plural': 'bookmark tags',
            },
        ),
    ]
